// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The AttachedClusters API provides a single centrally managed service
/// to register and manage Anthos attached clusters that run on customer's owned
/// infrastructure.
///
/// @Snippet(path: "AttachedClustersQuickstart")
public final class AttachedClustersClient: Clients.AttachedClustersProtocol, Sendable {
  let inner: any Clients.AttachedClustersStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

  /// Creates a new `AttachedClustersClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AttachedClustersStub = try Clients.AttachedClustersTransport(options)
    inner = Clients.AttachedClustersRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AttachedClustersLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// on a given Google Cloud Platform project and region.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_CreateAttachedCluster")
  public func createAttachedCluster(
    request: CreateAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAttachedCluster(request: request, options: options)
  }

  /// Creates a new
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// on a given Google Cloud Platform project and region.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_CreateAttachedCluster")
  public func createAttachedClusterPollingUntilDone(
    request: CreateAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AttachedCluster {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AttachedCluster>.State in
      return try op._extractStatus(AttachedCluster.self)
    }
    let rawOp = try await self.createAttachedCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AttachedCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates an
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_UpdateAttachedCluster")
  public func updateAttachedCluster(
    request: UpdateAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAttachedCluster(request: request, options: options)
  }

  /// Updates an
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_UpdateAttachedCluster")
  public func updateAttachedClusterPollingUntilDone(
    request: UpdateAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AttachedCluster {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AttachedCluster>.State in
      return try op._extractStatus(AttachedCluster.self)
    }
    let rawOp = try await self.updateAttachedCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AttachedCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Imports creates a new
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// by importing an existing Fleet Membership resource.
  ///
  /// Attached Clusters created before the introduction of the Anthos Multi-Cloud
  /// API can be imported through this method.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_ImportAttachedCluster")
  public func importAttachedCluster(
    request: ImportAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.importAttachedCluster(request: request, options: options)
  }

  /// Imports creates a new
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// by importing an existing Fleet Membership resource.
  ///
  /// Attached Clusters created before the introduction of the Anthos Multi-Cloud
  /// API can be imported through this method.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_ImportAttachedCluster")
  public func importAttachedClusterPollingUntilDone(
    request: ImportAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AttachedCluster {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AttachedCluster>.State in
      return try op._extractStatus(AttachedCluster.self)
    }
    let rawOp = try await self.importAttachedCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AttachedCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Describes a specific
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_GetAttachedCluster")
  public func getAttachedCluster(
    request: GetAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster {
    try await self.inner.getAttachedCluster(request: request, options: options)
  }

  /// Lists all [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster]
  /// resources on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_ListAttachedClusters")
  public func listAttachedClusters(
    request: ListAttachedClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse {
    try await self.inner.listAttachedClusters(request: request, options: options)
  }

  /// Deletes a specific
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_DeleteAttachedCluster")
  public func deleteAttachedCluster(
    request: DeleteAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAttachedCluster(request: request, options: options)
  }

  /// Deletes a specific
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_DeleteAttachedCluster")
  public func deleteAttachedClusterPollingUntilDone(
    request: DeleteAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAttachedCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Returns information, such as supported Kubernetes versions, on a given
  /// Google Cloud location.
  ///
  /// @Snippet(path: "AttachedClusters_GetAttachedServerConfig")
  public func getAttachedServerConfig(
    request: GetAttachedServerConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig {
    try await self.inner.getAttachedServerConfig(request: request, options: options)
  }

  /// Generates the install manifest to be installed on the target cluster.
  ///
  /// @Snippet(path: "AttachedClusters_GenerateAttachedClusterInstallManifest")
  public func generateAttachedClusterInstallManifest(
    request: GenerateAttachedClusterInstallManifestRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
    try await self.inner.generateAttachedClusterInstallManifest(request: request, options: options)
  }

  /// Generates an access token for a cluster agent.
  ///
  /// @Snippet(path: "AttachedClusters_GenerateAttachedClusterAgentToken")
  public func generateAttachedClusterAgentToken(
    request: GenerateAttachedClusterAgentTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse {
    try await self.inner.generateAttachedClusterAgentToken(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AttachedClusters_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AttachedClusters_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AttachedClusters_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AttachedClusters_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AttachedClustersClient`.
  ///
  /// To mock `AttachedClustersClient` change your functions to receive
  /// `some AttachedClustersProtocol` or `any AttachedClustersProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AttachedClustersProtocol: Sendable {
    /// See `AttachedClustersClient.createAttachedCluster`.
    func createAttachedCluster(
      request: CreateAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.createAttachedCluster`.
    func createAttachedClusterPollingUntilDone(
      request: CreateAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> AttachedCluster

    /// See `AttachedClustersClient.updateAttachedCluster`.
    func updateAttachedCluster(
      request: UpdateAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.updateAttachedCluster`.
    func updateAttachedClusterPollingUntilDone(
      request: UpdateAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> AttachedCluster

    /// See `AttachedClustersClient.importAttachedCluster`.
    func importAttachedCluster(
      request: ImportAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.importAttachedCluster`.
    func importAttachedClusterPollingUntilDone(
      request: ImportAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> AttachedCluster

    /// See `AttachedClustersClient.getAttachedCluster`.
    func getAttachedCluster(
      request: GetAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster

    /// See `AttachedClustersClient.listAttachedClusters`.
    func listAttachedClusters(
      request: ListAttachedClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse

    /// See `AttachedClustersClient.deleteAttachedCluster`.
    func deleteAttachedCluster(
      request: DeleteAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.deleteAttachedCluster`.
    func deleteAttachedClusterPollingUntilDone(
      request: DeleteAttachedClusterRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AttachedClustersClient.getAttachedServerConfig`.
    func getAttachedServerConfig(
      request: GetAttachedServerConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig

    /// See `AttachedClustersClient.generateAttachedClusterInstallManifest`.
    func generateAttachedClusterInstallManifest(
      request: GenerateAttachedClusterInstallManifestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse

    /// See `AttachedClustersClient.generateAttachedClusterAgentToken`.
    func generateAttachedClusterAgentToken(
      request: GenerateAttachedClusterAgentTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse

    /// See `AttachedClustersClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AttachedClustersClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AttachedClustersClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AttachedClustersProtocol {
  public func createAttachedCluster(request: CreateAttachedClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAttachedCluster(request: request, options: .init())
  }

  public func createAttachedCluster(
    request: CreateAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAttachedClusterPollingUntilDone(request: CreateAttachedClusterRequest)
    async throws -> AttachedCluster
  {
    return try await self.createAttachedClusterPollingUntilDone(request: request, options: .init())
  }

  public func createAttachedClusterPollingUntilDone(
    request: CreateAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AttachedCluster {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAttachedClusterPollingUntilDone(
    parent: Swift.String,
    attachedCluster: AttachedCluster?,
    attachedClusterId: Swift.String,
  ) async throws -> AttachedCluster {
    let request = CreateAttachedClusterRequest().with {
      $0.parent = parent
      $0.attachedCluster = attachedCluster
      $0.attachedClusterId = attachedClusterId
    }
    return try await self.createAttachedClusterPollingUntilDone(request: request)
  }

  public func updateAttachedCluster(request: UpdateAttachedClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAttachedCluster(request: request, options: .init())
  }

  public func updateAttachedCluster(
    request: UpdateAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAttachedClusterPollingUntilDone(request: UpdateAttachedClusterRequest)
    async throws -> AttachedCluster
  {
    return try await self.updateAttachedClusterPollingUntilDone(request: request, options: .init())
  }

  public func updateAttachedClusterPollingUntilDone(
    request: UpdateAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AttachedCluster {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAttachedClusterPollingUntilDone(
    attachedCluster: AttachedCluster?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> AttachedCluster {
    let request = UpdateAttachedClusterRequest().with {
      $0.attachedCluster = attachedCluster
      $0.updateMask = updateMask
    }
    return try await self.updateAttachedClusterPollingUntilDone(request: request)
  }

  public func importAttachedCluster(request: ImportAttachedClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.importAttachedCluster(request: request, options: .init())
  }

  public func importAttachedCluster(
    request: ImportAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func importAttachedClusterPollingUntilDone(request: ImportAttachedClusterRequest)
    async throws -> AttachedCluster
  {
    return try await self.importAttachedClusterPollingUntilDone(request: request, options: .init())
  }

  public func importAttachedClusterPollingUntilDone(
    request: ImportAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AttachedCluster {
    throw GoogleGax.RequestError.unimplemented
  }

  public func importAttachedClusterPollingUntilDone(
    parent: Swift.String,
    fleetMembership: Swift.String,
  ) async throws -> AttachedCluster {
    let request = ImportAttachedClusterRequest().with {
      $0.parent = parent
      $0.fleetMembership = fleetMembership
    }
    return try await self.importAttachedClusterPollingUntilDone(request: request)
  }

  public func getAttachedCluster(request: GetAttachedClusterRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AttachedCluster
  {
    try await self.getAttachedCluster(request: request, options: .init())
  }

  public func getAttachedCluster(
    request: GetAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAttachedCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster {
    let request = GetAttachedClusterRequest().with {
      $0.name = name
    }
    return try await self.getAttachedCluster(request: request)
  }

  public func listAttachedClusters(request: ListAttachedClustersRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse
  {
    try await self.listAttachedClusters(request: request, options: .init())
  }

  public func listAttachedClusters(
    request: ListAttachedClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAttachedClustersByItems(
    request: ListAttachedClustersRequest
  ) -> some AsyncSequence<AttachedCluster, Swift.Error> & Sendable {
    self.listAttachedClustersByItems(request: request, options: .init())
  }

  /// Lists all [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster]
  /// resources on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_ListAttachedClusters")
  public func listAttachedClustersByItems(
    request: ListAttachedClustersRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AttachedCluster, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse in
      var request = request
      request.pageToken = token
      return try await self.listAttachedClusters(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listAttachedClustersByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<AttachedCluster, Swift.Error> & Sendable {
    let request = ListAttachedClustersRequest().with {
      $0.parent = parent
    }
    return self.listAttachedClustersByItems(request: request)
  }

  public func deleteAttachedCluster(request: DeleteAttachedClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAttachedCluster(request: request, options: .init())
  }

  public func deleteAttachedCluster(
    request: DeleteAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAttachedClusterPollingUntilDone(request: DeleteAttachedClusterRequest)
    async throws
  {
    try await self.deleteAttachedClusterPollingUntilDone(request: request, options: .init())
  }

  public func deleteAttachedClusterPollingUntilDone(
    request: DeleteAttachedClusterRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAttachedClusterPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteAttachedClusterRequest().with {
      $0.name = name
    }
    try await self.deleteAttachedClusterPollingUntilDone(request: request)
  }

  public func getAttachedServerConfig(request: GetAttachedServerConfigRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig
  {
    try await self.getAttachedServerConfig(request: request, options: .init())
  }

  public func getAttachedServerConfig(
    request: GetAttachedServerConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAttachedServerConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig {
    let request = GetAttachedServerConfigRequest().with {
      $0.name = name
    }
    return try await self.getAttachedServerConfig(request: request)
  }

  public func generateAttachedClusterInstallManifest(
    request: GenerateAttachedClusterInstallManifestRequest
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
    try await self.generateAttachedClusterInstallManifest(request: request, options: .init())
  }

  public func generateAttachedClusterInstallManifest(
    request: GenerateAttachedClusterInstallManifestRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func generateAttachedClusterInstallManifest(
    parent: Swift.String,
    attachedClusterId: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
    let request = GenerateAttachedClusterInstallManifestRequest().with {
      $0.parent = parent
      $0.attachedClusterId = attachedClusterId
    }
    return try await self.generateAttachedClusterInstallManifest(request: request)
  }

  public func generateAttachedClusterAgentToken(request: GenerateAttachedClusterAgentTokenRequest)
    async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse
  {
    try await self.generateAttachedClusterAgentToken(request: request, options: .init())
  }

  public func generateAttachedClusterAgentToken(
    request: GenerateAttachedClusterAgentTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AttachedClusters_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
