// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information about a supported Attached Clusters platform version.
public struct AttachedPlatformVersionInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Platform version name.
  public var version: Swift.String = Swift.String()

  /// Optional. True if the version is available for attachedcluster creation. If
  /// a version is enabled, it can be used to attach new clusters.
  public var enabled: Swift.Bool = Swift.Bool()

  /// Optional. True if this cluster version belongs to a minor version that has
  /// reached its end of life and is no longer in scope to receive security and
  /// bug fixes.
  public var endOfLife: Swift.Bool = Swift.Bool()

  /// Optional. The estimated date (in Pacific Time) when this cluster version
  /// will reach its end of life. Or if this version is no longer supported (the
  /// `end_of_life` field is true), this is the actual date (in Pacific time)
  /// when the version reached its end of life.
  public var endOfLifeDate: GoogleType.Date? = nil

  /// Optional. The date (in Pacific Time) when the cluster version was released.
  public var releaseDate: GoogleType.Date? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AttachedPlatformVersionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttachedPlatformVersionInfo().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let version = CodingKeys(stringValue: "version")
    static let enabled = CodingKeys(stringValue: "enabled")
    static let endOfLife = CodingKeys(stringValue: "endOfLife")
    static let endOfLifeDate = CodingKeys(stringValue: "endOfLifeDate")
    static let releaseDate = CodingKeys(stringValue: "releaseDate")

    static let _knownKeys: Set<Swift.String> = [
      "version",
      "enabled",
      "endOfLife",
      "endOfLifeDate",
      "releaseDate",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
      self.enabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .endOfLife) {
      self.endOfLife = value
    }
    self.endOfLifeDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .endOfLifeDate)
    self.releaseDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .releaseDate)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.enabled, forKey: .enabled)
    try container.encode(self.endOfLife, forKey: .endOfLife)
    try container.encodeIfPresent(self.endOfLifeDate, forKey: .endOfLifeDate)
    try container.encodeIfPresent(self.releaseDate, forKey: .releaseDate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AttachedPlatformVersionInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
