// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration related to the cluster RBAC settings.
@available(*, deprecated)
public struct AwsAuthorization: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Users that can perform operations as a cluster admin. A managed
  /// ClusterRoleBinding will be created to grant the `cluster-admin` ClusterRole
  /// to the users. Up to ten admin users can be provided.
  ///
  /// For more info on RBAC, see
  /// https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
  public var adminUsers: [AwsClusterUser] = []

  /// Optional. Groups of users that can perform operations as a cluster admin. A
  /// managed ClusterRoleBinding will be created to grant the `cluster-admin`
  /// ClusterRole to the groups. Up to ten admin groups can be provided.
  ///
  /// For more info on RBAC, see
  /// https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
  public var adminGroups: [AwsClusterGroup] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AwsAuthorization`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsAuthorization().with { $0.adminUsers = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let adminUsers = CodingKeys(stringValue: "adminUsers")
    static let adminGroups = CodingKeys(stringValue: "adminGroups")

    static let _knownKeys: Set<Swift.String> = [
      "adminUsers",
      "adminGroups",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([AwsClusterUser].self, forKey: .adminUsers) {
      self.adminUsers = value
    }
    if let value = try container.decodeIfPresent([AwsClusterGroup].self, forKey: .adminGroups) {
      self.adminGroups = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.adminUsers, forKey: .adminUsers)
    try container.encode(self.adminGroups, forKey: .adminGroups)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AwsAuthorization`: `"type.googleapis.com/google.cloud.gkemulticloud.v1.AwsAuthorization"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AwsAuthorization"
  }

  /// Initialize an instance of `AwsAuthorization` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkemulticloud.v1.AwsAuthorization"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AwsAuthorization` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
