// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ClusterNetworking defines cluster-wide networking configuration.
///
/// Anthos clusters on AWS run on a single VPC. This includes control
/// plane replicas and node pool nodes.
@available(*, deprecated)
public struct AwsClusterNetworking: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The VPC associated with the cluster. All component clusters
  /// (i.e. control plane and node pools) run on a single VPC.
  ///
  /// This field cannot be changed after creation.
  public var vpcId: Swift.String = Swift.String()

  /// Required. All pods in the cluster are assigned an IPv4 address from these
  /// ranges. Only a single range is supported. This field cannot be changed
  /// after creation.
  public var podAddressCidrBlocks: [Swift.String] = []

  /// Required. All services in the cluster are assigned an IPv4 address from
  /// these ranges. Only a single range is supported. This field cannot be
  /// changed after creation.
  public var serviceAddressCidrBlocks: [Swift.String] = []

  /// Optional. Disable the per node pool subnet security group rules on the
  /// control plane security group. When set to true, you must also provide one
  /// or more security groups that ensure node pools are able to send requests to
  /// the control plane on TCP/443 and TCP/8132. Failure to do so may result in
  /// unavailable node pools.
  public var perNodePoolSgRulesDisabled: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AwsClusterNetworking`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsClusterNetworking().with { $0.vpcId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vpcId = CodingKeys(stringValue: "vpcId")
    static let podAddressCidrBlocks = CodingKeys(stringValue: "podAddressCidrBlocks")
    static let serviceAddressCidrBlocks = CodingKeys(stringValue: "serviceAddressCidrBlocks")
    static let perNodePoolSgRulesDisabled = CodingKeys(stringValue: "perNodePoolSgRulesDisabled")

    static let _knownKeys: Set<Swift.String> = [
      "vpcId",
      "podAddressCidrBlocks",
      "serviceAddressCidrBlocks",
      "perNodePoolSgRulesDisabled",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vpcId) {
      self.vpcId = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .podAddressCidrBlocks)
    {
      self.podAddressCidrBlocks = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .serviceAddressCidrBlocks)
    {
      self.serviceAddressCidrBlocks = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .perNodePoolSgRulesDisabled)
    {
      self.perNodePoolSgRulesDisabled = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.vpcId, forKey: .vpcId)
    try container.encode(self.podAddressCidrBlocks, forKey: .podAddressCidrBlocks)
    try container.encode(self.serviceAddressCidrBlocks, forKey: .serviceAddressCidrBlocks)
    try container.encode(self.perNodePoolSgRulesDisabled, forKey: .perNodePoolSgRulesDisabled)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AwsClusterNetworking"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
