// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ControlPlane defines common parameters between control plane nodes.
@available(*, deprecated)
public struct AwsControlPlane: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The Kubernetes version to run on control plane replicas
  /// (e.g. `1.19.10-gke.1000`).
  ///
  /// You can list all supported versions on a given Google Cloud region by
  /// calling
  /// [GetAwsServerConfig][google.cloud.gkemulticloud.v1.AwsClusters.GetAwsServerConfig].
  ///
  /// [google.cloud.gkemulticloud.v1.AwsClusters.GetAwsServerConfig]: <doc:AwsClustersClient/getAwsServerConfig(request:options:)>
  public var version: Swift.String = Swift.String()

  /// Optional. The AWS instance type.
  ///
  /// When unspecified, it uses a default based on the cluster's version.
  public var instanceType: Swift.String = Swift.String()

  /// Optional. SSH configuration for how to access the underlying control plane
  /// machines.
  public var sshConfig: AwsSshConfig? = nil

  /// Required. The list of subnets where control plane replicas will run.
  /// A replica will be provisioned on each subnet and up to three values
  /// can be provided.
  /// Each subnet must be in a different AWS Availability Zone (AZ).
  public var subnetIds: [Swift.String] = []

  /// Optional. The IDs of additional security groups to add to control plane
  /// replicas. The Anthos Multi-Cloud API will automatically create and manage
  /// security groups with the minimum rules needed for a functioning cluster.
  public var securityGroupIds: [Swift.String] = []

  /// Required. The name or ARN of the AWS IAM instance profile to assign to each
  /// control plane replica.
  public var iamInstanceProfile: Swift.String = Swift.String()

  /// Optional. Configuration related to the root volume provisioned for each
  /// control plane replica.
  ///
  /// Volumes will be provisioned in the availability zone associated
  /// with the corresponding subnet.
  ///
  /// When unspecified, it defaults to 32 GiB with the GP2 volume type.
  public var rootVolume: AwsVolumeTemplate? = nil

  /// Optional. Configuration related to the main volume provisioned for each
  /// control plane replica.
  /// The main volume is in charge of storing all of the cluster's etcd state.
  ///
  /// Volumes will be provisioned in the availability zone associated
  /// with the corresponding subnet.
  ///
  /// When unspecified, it defaults to 8 GiB with the GP2 volume type.
  public var mainVolume: AwsVolumeTemplate? = nil

  /// Required. The ARN of the AWS KMS key used to encrypt cluster secrets.
  public var databaseEncryption: AwsDatabaseEncryption? = nil

  /// Optional. A set of AWS resource tags to propagate to all underlying managed
  /// AWS resources.
  ///
  /// Specify at most 50 pairs containing alphanumerics, spaces, and symbols
  /// (.+-=_:@/). Keys can be up to 127 Unicode characters. Values can be up to
  /// 255 Unicode characters.
  public var tags: [Swift.String: Swift.String] = [:]

  /// Required. Authentication configuration for management of AWS resources.
  public var awsServicesAuthentication: AwsServicesAuthentication? = nil

  /// Optional. Proxy configuration for outbound HTTP(S) traffic.
  public var proxyConfig: AwsProxyConfig? = nil

  /// Required. Config encryption for user data.
  public var configEncryption: AwsConfigEncryption? = nil

  /// Optional. The placement to use on control plane instances.
  /// When unspecified, the VPC's default tenancy will be used.
  public var instancePlacement: AwsInstancePlacement? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AwsControlPlane`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsControlPlane().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let version = CodingKeys(stringValue: "version")
    static let instanceType = CodingKeys(stringValue: "instanceType")
    static let sshConfig = CodingKeys(stringValue: "sshConfig")
    static let subnetIds = CodingKeys(stringValue: "subnetIds")
    static let securityGroupIds = CodingKeys(stringValue: "securityGroupIds")
    static let iamInstanceProfile = CodingKeys(stringValue: "iamInstanceProfile")
    static let rootVolume = CodingKeys(stringValue: "rootVolume")
    static let mainVolume = CodingKeys(stringValue: "mainVolume")
    static let databaseEncryption = CodingKeys(stringValue: "databaseEncryption")
    static let tags = CodingKeys(stringValue: "tags")
    static let awsServicesAuthentication = CodingKeys(stringValue: "awsServicesAuthentication")
    static let proxyConfig = CodingKeys(stringValue: "proxyConfig")
    static let configEncryption = CodingKeys(stringValue: "configEncryption")
    static let instancePlacement = CodingKeys(stringValue: "instancePlacement")

    static let _knownKeys: Set<Swift.String> = [
      "version",
      "instanceType",
      "sshConfig",
      "subnetIds",
      "securityGroupIds",
      "iamInstanceProfile",
      "rootVolume",
      "mainVolume",
      "databaseEncryption",
      "tags",
      "awsServicesAuthentication",
      "proxyConfig",
      "configEncryption",
      "instancePlacement",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceType) {
      self.instanceType = value
    }
    self.sshConfig = try container.decodeIfPresent(AwsSshConfig.self, forKey: .sshConfig)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .subnetIds) {
      self.subnetIds = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .securityGroupIds) {
      self.securityGroupIds = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .iamInstanceProfile) {
      self.iamInstanceProfile = value
    }
    self.rootVolume = try container.decodeIfPresent(AwsVolumeTemplate.self, forKey: .rootVolume)
    self.mainVolume = try container.decodeIfPresent(AwsVolumeTemplate.self, forKey: .mainVolume)
    self.databaseEncryption = try container.decodeIfPresent(
      AwsDatabaseEncryption.self, forKey: .databaseEncryption)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    self.awsServicesAuthentication = try container.decodeIfPresent(
      AwsServicesAuthentication.self, forKey: .awsServicesAuthentication)
    self.proxyConfig = try container.decodeIfPresent(AwsProxyConfig.self, forKey: .proxyConfig)
    self.configEncryption = try container.decodeIfPresent(
      AwsConfigEncryption.self, forKey: .configEncryption)
    self.instancePlacement = try container.decodeIfPresent(
      AwsInstancePlacement.self, forKey: .instancePlacement)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.instanceType, forKey: .instanceType)
    try container.encodeIfPresent(self.sshConfig, forKey: .sshConfig)
    try container.encode(self.subnetIds, forKey: .subnetIds)
    try container.encode(self.securityGroupIds, forKey: .securityGroupIds)
    try container.encode(self.iamInstanceProfile, forKey: .iamInstanceProfile)
    try container.encodeIfPresent(self.rootVolume, forKey: .rootVolume)
    try container.encodeIfPresent(self.mainVolume, forKey: .mainVolume)
    try container.encodeIfPresent(self.databaseEncryption, forKey: .databaseEncryption)
    try container.encode(self.tags, forKey: .tags)
    try container.encodeIfPresent(
      self.awsServicesAuthentication, forKey: .awsServicesAuthentication)
    try container.encodeIfPresent(self.proxyConfig, forKey: .proxyConfig)
    try container.encodeIfPresent(self.configEncryption, forKey: .configEncryption)
    try container.encodeIfPresent(self.instancePlacement, forKey: .instancePlacement)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AwsControlPlane`: `"type.googleapis.com/google.cloud.gkemulticloud.v1.AwsControlPlane"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AwsControlPlane"
  }

  /// Initialize an instance of `AwsControlPlane` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkemulticloud.v1.AwsControlPlane"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AwsControlPlane` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
