// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Parameters that describe the nodes in a cluster.
@available(*, deprecated)
public struct AwsNodeConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The EC2 instance type when creating on-Demand instances.
  ///
  /// If unspecified during node pool creation, a default will be chosen based on
  /// the node pool version, and assigned to this field.
  public var instanceType: Swift.String = Swift.String()

  /// Optional. Template for the root volume provisioned for node pool nodes.
  /// Volumes will be provisioned in the availability zone assigned
  /// to the node pool subnet.
  ///
  /// When unspecified, it defaults to 32 GiB with the GP2 volume type.
  public var rootVolume: AwsVolumeTemplate? = nil

  /// Optional. The initial taints assigned to nodes of this node pool.
  public var taints: [NodeTaint] = []

  /// Optional. The initial labels assigned to nodes of this node pool. An object
  /// containing a list of "key": value pairs. Example: { "name": "wrench",
  /// "mass": "1.3kg", "count": "3" }.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Key/value metadata to assign to each underlying AWS resource.
  /// Specify at most 50 pairs containing alphanumerics, spaces, and symbols
  /// (.+-=_:@/). Keys can be up to 127 Unicode characters. Values can be up to
  /// 255 Unicode characters.
  public var tags: [Swift.String: Swift.String] = [:]

  /// Required. The name or ARN of the AWS IAM instance profile to assign to
  /// nodes in the pool.
  public var iamInstanceProfile: Swift.String = Swift.String()

  /// Optional. The OS image type to use on node pool instances.
  /// Can be unspecified, or have a value of `ubuntu`.
  ///
  /// When unspecified, it defaults to `ubuntu`.
  public var imageType: Swift.String = Swift.String()

  /// Optional. The SSH configuration.
  public var sshConfig: AwsSshConfig? = nil

  /// Optional. The IDs of additional security groups to add to nodes in this
  /// pool. The manager will automatically create security groups with minimum
  /// rules needed for a functioning cluster.
  public var securityGroupIds: [Swift.String] = []

  /// Optional. Proxy configuration for outbound HTTP(S) traffic.
  public var proxyConfig: AwsProxyConfig? = nil

  /// Required. Config encryption for user data.
  public var configEncryption: AwsConfigEncryption? = nil

  /// Optional. Placement related info for this node.
  /// When unspecified, the VPC's default tenancy will be used.
  public var instancePlacement: AwsInstancePlacement? = nil

  /// Optional. Configuration related to CloudWatch metrics collection on the
  /// Auto Scaling group of the node pool.
  ///
  /// When unspecified, metrics collection is disabled.
  public var autoscalingMetricsCollection: AwsAutoscalingGroupMetricsCollection? = nil

  /// Optional. Configuration for provisioning EC2 Spot instances
  ///
  /// When specified, the node pool will provision Spot instances from the set
  /// of spot_config.instance_types.
  /// This field is mutually exclusive with `instance_type`.
  public var spotConfig: SpotConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AwsNodeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsNodeConfig().with { $0.instanceType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let instanceType = CodingKeys(stringValue: "instanceType")
    static let rootVolume = CodingKeys(stringValue: "rootVolume")
    static let taints = CodingKeys(stringValue: "taints")
    static let labels = CodingKeys(stringValue: "labels")
    static let tags = CodingKeys(stringValue: "tags")
    static let iamInstanceProfile = CodingKeys(stringValue: "iamInstanceProfile")
    static let imageType = CodingKeys(stringValue: "imageType")
    static let sshConfig = CodingKeys(stringValue: "sshConfig")
    static let securityGroupIds = CodingKeys(stringValue: "securityGroupIds")
    static let proxyConfig = CodingKeys(stringValue: "proxyConfig")
    static let configEncryption = CodingKeys(stringValue: "configEncryption")
    static let instancePlacement = CodingKeys(stringValue: "instancePlacement")
    static let autoscalingMetricsCollection = CodingKeys(
      stringValue: "autoscalingMetricsCollection")
    static let spotConfig = CodingKeys(stringValue: "spotConfig")

    static let _knownKeys: Set<Swift.String> = [
      "instanceType",
      "rootVolume",
      "taints",
      "labels",
      "tags",
      "iamInstanceProfile",
      "imageType",
      "sshConfig",
      "securityGroupIds",
      "proxyConfig",
      "configEncryption",
      "instancePlacement",
      "autoscalingMetricsCollection",
      "spotConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceType) {
      self.instanceType = value
    }
    self.rootVolume = try container.decodeIfPresent(AwsVolumeTemplate.self, forKey: .rootVolume)
    if let value = try container.decodeIfPresent([NodeTaint].self, forKey: .taints) {
      self.taints = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .iamInstanceProfile) {
      self.iamInstanceProfile = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageType) {
      self.imageType = value
    }
    self.sshConfig = try container.decodeIfPresent(AwsSshConfig.self, forKey: .sshConfig)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .securityGroupIds) {
      self.securityGroupIds = value
    }
    self.proxyConfig = try container.decodeIfPresent(AwsProxyConfig.self, forKey: .proxyConfig)
    self.configEncryption = try container.decodeIfPresent(
      AwsConfigEncryption.self, forKey: .configEncryption)
    self.instancePlacement = try container.decodeIfPresent(
      AwsInstancePlacement.self, forKey: .instancePlacement)
    self.autoscalingMetricsCollection = try container.decodeIfPresent(
      AwsAutoscalingGroupMetricsCollection.self, forKey: .autoscalingMetricsCollection)
    self.spotConfig = try container.decodeIfPresent(SpotConfig.self, forKey: .spotConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.instanceType, forKey: .instanceType)
    try container.encodeIfPresent(self.rootVolume, forKey: .rootVolume)
    try container.encode(self.taints, forKey: .taints)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.iamInstanceProfile, forKey: .iamInstanceProfile)
    try container.encode(self.imageType, forKey: .imageType)
    try container.encodeIfPresent(self.sshConfig, forKey: .sshConfig)
    try container.encode(self.securityGroupIds, forKey: .securityGroupIds)
    try container.encodeIfPresent(self.proxyConfig, forKey: .proxyConfig)
    try container.encodeIfPresent(self.configEncryption, forKey: .configEncryption)
    try container.encodeIfPresent(self.instancePlacement, forKey: .instancePlacement)
    try container.encodeIfPresent(
      self.autoscalingMetricsCollection, forKey: .autoscalingMetricsCollection)
    try container.encodeIfPresent(self.spotConfig, forKey: .spotConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AwsNodeConfig`: `"type.googleapis.com/google.cloud.gkemulticloud.v1.AwsNodeConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AwsNodeConfig"
  }

  /// Initialize an instance of `AwsNodeConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkemulticloud.v1.AwsNodeConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AwsNodeConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
