// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AwsServerConfig is the configuration of GKE cluster on AWS.
@available(*, deprecated)
public struct AwsServerConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the config.
  public var name: Swift.String = Swift.String()

  /// List of all released Kubernetes versions, including ones which are end of
  /// life and can no longer be used.  Filter by the `enabled`
  /// property to limit to currently available versions.
  /// Valid versions supported for both create and update operations
  public var validVersions: [AwsK8sVersionInfo] = []

  /// The list of supported AWS regions.
  public var supportedAwsRegions: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AwsServerConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsServerConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let validVersions = CodingKeys(stringValue: "validVersions")
    static let supportedAwsRegions = CodingKeys(stringValue: "supportedAwsRegions")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "validVersions",
      "supportedAwsRegions",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([AwsK8sVersionInfo].self, forKey: .validVersions) {
      self.validVersions = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .supportedAwsRegions)
    {
      self.supportedAwsRegions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.validVersions, forKey: .validVersions)
    try container.encode(self.supportedAwsRegions, forKey: .supportedAwsRegions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AwsServerConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
