// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The AzureClusters API provides a single centrally managed service
/// to create and manage Anthos clusters that run on Azure infrastructure.
///
/// @Snippet(path: "AzureClustersQuickstart")
@available(*, deprecated)
public final class AzureClustersClient: Clients.AzureClustersProtocol, Sendable {
  let inner: any Clients.AzureClustersStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

  /// Creates a new `AzureClustersClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AzureClustersStub = try Clients.AzureClustersTransport(options)
    inner = Clients.AzureClustersRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AzureClustersLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new [AzureClient][google.cloud.gkemulticloud.v1.AzureClient]
  /// resource on a given Google Cloud project and region.
  ///
  /// `AzureClient` resources hold client authentication
  /// information needed by the Anthos Multicloud API to manage Azure resources
  /// on your Azure subscription on your behalf.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_CreateAzureClient")
  @available(*, deprecated)
  public func createAzureClient(
    request: CreateAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAzureClient(request: request, options: options)
  }

  /// Creates a new [AzureClient][google.cloud.gkemulticloud.v1.AzureClient]
  /// resource on a given Google Cloud project and region.
  ///
  /// `AzureClient` resources hold client authentication
  /// information needed by the Anthos Multicloud API to manage Azure resources
  /// on your Azure subscription on your behalf.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_CreateAzureClient")
  @available(*, deprecated)
  public func createAzureClientPollingUntilDone(
    request: CreateAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureClient {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AzureClient>.State in
      return try op._extractStatus(AzureClient.self)
    }
    let rawOp = try await self.createAzureClient(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<AzureClient>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Describes a specific
  /// [AzureClient][google.cloud.gkemulticloud.v1.AzureClient] resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  ///
  /// @Snippet(path: "AzureClusters_GetAzureClient")
  @available(*, deprecated)
  public func getAzureClient(
    request: GetAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureClient {
    try await self.inner.getAzureClient(request: request, options: options)
  }

  /// Lists all [AzureClient][google.cloud.gkemulticloud.v1.AzureClient]
  /// resources on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  ///
  /// @Snippet(path: "AzureClusters_ListAzureClients")
  @available(*, deprecated)
  public func listAzureClients(
    request: ListAzureClientsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureClientsResponse {
    try await self.inner.listAzureClients(request: request, options: options)
  }

  /// Deletes a specific [AzureClient][google.cloud.gkemulticloud.v1.AzureClient]
  /// resource.
  ///
  /// If the client is used by one or more clusters, deletion will
  /// fail and a `FAILED_PRECONDITION` error will be returned.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_DeleteAzureClient")
  @available(*, deprecated)
  public func deleteAzureClient(
    request: DeleteAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAzureClient(request: request, options: options)
  }

  /// Deletes a specific [AzureClient][google.cloud.gkemulticloud.v1.AzureClient]
  /// resource.
  ///
  /// If the client is used by one or more clusters, deletion will
  /// fail and a `FAILED_PRECONDITION` error will be returned.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_DeleteAzureClient")
  @available(*, deprecated)
  public func deleteAzureClientPollingUntilDone(
    request: DeleteAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAzureClient(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Creates a new [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster]
  /// resource on a given Google Cloud Platform project and region.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_CreateAzureCluster")
  @available(*, deprecated)
  public func createAzureCluster(
    request: CreateAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAzureCluster(request: request, options: options)
  }

  /// Creates a new [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster]
  /// resource on a given Google Cloud Platform project and region.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_CreateAzureCluster")
  @available(*, deprecated)
  public func createAzureClusterPollingUntilDone(
    request: CreateAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureCluster {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AzureCluster>.State in
      return try op._extractStatus(AzureCluster.self)
    }
    let rawOp = try await self.createAzureCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AzureCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates an [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  ///
  /// @Snippet(path: "AzureClusters_UpdateAzureCluster")
  @available(*, deprecated)
  public func updateAzureCluster(
    request: UpdateAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAzureCluster(request: request, options: options)
  }

  /// Updates an [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  ///
  /// @Snippet(path: "AzureClusters_UpdateAzureCluster")
  @available(*, deprecated)
  public func updateAzureClusterPollingUntilDone(
    request: UpdateAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureCluster {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AzureCluster>.State in
      return try op._extractStatus(AzureCluster.self)
    }
    let rawOp = try await self.updateAzureCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AzureCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Describes a specific
  /// [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster] resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  ///
  /// @Snippet(path: "AzureClusters_GetAzureCluster")
  @available(*, deprecated)
  public func getAzureCluster(
    request: GetAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureCluster {
    try await self.inner.getAzureCluster(request: request, options: options)
  }

  /// Lists all [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster]
  /// resources on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  ///
  /// @Snippet(path: "AzureClusters_ListAzureClusters")
  @available(*, deprecated)
  public func listAzureClusters(
    request: ListAzureClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureClustersResponse {
    try await self.inner.listAzureClusters(request: request, options: options)
  }

  /// Deletes a specific
  /// [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster] resource.
  ///
  /// Fails if the cluster has one or more associated
  /// [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool] resources.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_DeleteAzureCluster")
  @available(*, deprecated)
  public func deleteAzureCluster(
    request: DeleteAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAzureCluster(request: request, options: options)
  }

  /// Deletes a specific
  /// [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster] resource.
  ///
  /// Fails if the cluster has one or more associated
  /// [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool] resources.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_DeleteAzureCluster")
  @available(*, deprecated)
  public func deleteAzureClusterPollingUntilDone(
    request: DeleteAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAzureCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Generates an access token for a cluster agent.
  ///
  /// @Snippet(path: "AzureClusters_GenerateAzureClusterAgentToken")
  @available(*, deprecated)
  public func generateAzureClusterAgentToken(
    request: GenerateAzureClusterAgentTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAzureClusterAgentTokenResponse {
    try await self.inner.generateAzureClusterAgentToken(request: request, options: options)
  }

  /// Generates a short-lived access token to authenticate to a given
  /// [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster] resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  ///
  /// @Snippet(path: "AzureClusters_GenerateAzureAccessToken")
  @available(*, deprecated)
  public func generateAzureAccessToken(
    request: GenerateAzureAccessTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAzureAccessTokenResponse {
    try await self.inner.generateAzureAccessToken(request: request, options: options)
  }

  /// Creates a new [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool],
  /// attached to a given
  /// [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster].
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_CreateAzureNodePool")
  @available(*, deprecated)
  public func createAzureNodePool(
    request: CreateAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAzureNodePool(request: request, options: options)
  }

  /// Creates a new [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool],
  /// attached to a given
  /// [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster].
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_CreateAzureNodePool")
  @available(*, deprecated)
  public func createAzureNodePoolPollingUntilDone(
    request: CreateAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureNodePool {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AzureNodePool>.State in
      return try op._extractStatus(AzureNodePool.self)
    }
    let rawOp = try await self.createAzureNodePool(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AzureNodePool>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates an [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool].
  ///
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  ///
  /// @Snippet(path: "AzureClusters_UpdateAzureNodePool")
  @available(*, deprecated)
  public func updateAzureNodePool(
    request: UpdateAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAzureNodePool(request: request, options: options)
  }

  /// Updates an [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool].
  ///
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  ///
  /// @Snippet(path: "AzureClusters_UpdateAzureNodePool")
  @available(*, deprecated)
  public func updateAzureNodePoolPollingUntilDone(
    request: UpdateAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureNodePool {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AzureNodePool>.State in
      return try op._extractStatus(AzureNodePool.self)
    }
    let rawOp = try await self.updateAzureNodePool(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AzureNodePool>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Describes a specific
  /// [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool] resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  ///
  /// @Snippet(path: "AzureClusters_GetAzureNodePool")
  @available(*, deprecated)
  public func getAzureNodePool(
    request: GetAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureNodePool {
    try await self.inner.getAzureNodePool(request: request, options: options)
  }

  /// Lists all [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool]
  /// resources on a given
  /// [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  ///
  /// @Snippet(path: "AzureClusters_ListAzureNodePools")
  @available(*, deprecated)
  public func listAzureNodePools(
    request: ListAzureNodePoolsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureNodePoolsResponse {
    try await self.inner.listAzureNodePools(request: request, options: options)
  }

  /// Deletes a specific
  /// [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool] resource.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_DeleteAzureNodePool")
  @available(*, deprecated)
  public func deleteAzureNodePool(
    request: DeleteAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAzureNodePool(request: request, options: options)
  }

  /// Deletes a specific
  /// [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool] resource.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AzureClusters_DeleteAzureNodePool")
  @available(*, deprecated)
  public func deleteAzureNodePoolPollingUntilDone(
    request: DeleteAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAzureNodePool(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Gets the OIDC discovery document for the cluster.
  /// See the
  /// [OpenID Connect Discovery 1.0
  /// specification](https://openid.net/specs/openid-connect-discovery-1_0.html)
  /// for details.
  ///
  /// @Snippet(path: "AzureClusters_GetAzureOpenIdConfig")
  @available(*, deprecated)
  public func getAzureOpenIdConfig(
    request: GetAzureOpenIdConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureOpenIdConfig {
    try await self.inner.getAzureOpenIdConfig(request: request, options: options)
  }

  /// Gets the public component of the cluster signing keys in
  /// JSON Web Key format.
  ///
  /// @Snippet(path: "AzureClusters_GetAzureJsonWebKeys")
  @available(*, deprecated)
  public func getAzureJsonWebKeys(
    request: GetAzureJsonWebKeysRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureJsonWebKeys {
    try await self.inner.getAzureJsonWebKeys(request: request, options: options)
  }

  /// Returns information, such as supported Azure regions and Kubernetes
  /// versions, on a given Google Cloud location.
  ///
  /// @Snippet(path: "AzureClusters_GetAzureServerConfig")
  @available(*, deprecated)
  public func getAzureServerConfig(
    request: GetAzureServerConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureServerConfig {
    try await self.inner.getAzureServerConfig(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AzureClusters_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AzureClusters_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AzureClusters_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AzureClusters_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AzureClustersClient`.
  ///
  /// To mock `AzureClustersClient` change your functions to receive
  /// `some AzureClustersProtocol` or `any AzureClustersProtocol`
  /// and pass a mock implementation in your tests.
  @available(*, deprecated)
  public protocol AzureClustersProtocol: Sendable {
    /// See `AzureClustersClient.createAzureClient`.
    @available(*, deprecated)
    func createAzureClient(
      request: CreateAzureClientRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AzureClustersClient.createAzureClient`.
    @available(*, deprecated)
    func createAzureClientPollingUntilDone(
      request: CreateAzureClientRequest, options: GoogleGax.RequestOptions
    ) async throws -> AzureClient

    /// See `AzureClustersClient.getAzureClient`.
    @available(*, deprecated)
    func getAzureClient(
      request: GetAzureClientRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AzureClient

    /// See `AzureClustersClient.listAzureClients`.
    @available(*, deprecated)
    func listAzureClients(
      request: ListAzureClientsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureClientsResponse

    /// See `AzureClustersClient.deleteAzureClient`.
    @available(*, deprecated)
    func deleteAzureClient(
      request: DeleteAzureClientRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AzureClustersClient.deleteAzureClient`.
    @available(*, deprecated)
    func deleteAzureClientPollingUntilDone(
      request: DeleteAzureClientRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AzureClustersClient.createAzureCluster`.
    @available(*, deprecated)
    func createAzureCluster(
      request: CreateAzureClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AzureClustersClient.createAzureCluster`.
    @available(*, deprecated)
    func createAzureClusterPollingUntilDone(
      request: CreateAzureClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> AzureCluster

    /// See `AzureClustersClient.updateAzureCluster`.
    @available(*, deprecated)
    func updateAzureCluster(
      request: UpdateAzureClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AzureClustersClient.updateAzureCluster`.
    @available(*, deprecated)
    func updateAzureClusterPollingUntilDone(
      request: UpdateAzureClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> AzureCluster

    /// See `AzureClustersClient.getAzureCluster`.
    @available(*, deprecated)
    func getAzureCluster(
      request: GetAzureClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AzureCluster

    /// See `AzureClustersClient.listAzureClusters`.
    @available(*, deprecated)
    func listAzureClusters(
      request: ListAzureClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureClustersResponse

    /// See `AzureClustersClient.deleteAzureCluster`.
    @available(*, deprecated)
    func deleteAzureCluster(
      request: DeleteAzureClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AzureClustersClient.deleteAzureCluster`.
    @available(*, deprecated)
    func deleteAzureClusterPollingUntilDone(
      request: DeleteAzureClusterRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AzureClustersClient.generateAzureClusterAgentToken`.
    @available(*, deprecated)
    func generateAzureClusterAgentToken(
      request: GenerateAzureClusterAgentTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAzureClusterAgentTokenResponse

    /// See `AzureClustersClient.generateAzureAccessToken`.
    @available(*, deprecated)
    func generateAzureAccessToken(
      request: GenerateAzureAccessTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAzureAccessTokenResponse

    /// See `AzureClustersClient.createAzureNodePool`.
    @available(*, deprecated)
    func createAzureNodePool(
      request: CreateAzureNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AzureClustersClient.createAzureNodePool`.
    @available(*, deprecated)
    func createAzureNodePoolPollingUntilDone(
      request: CreateAzureNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> AzureNodePool

    /// See `AzureClustersClient.updateAzureNodePool`.
    @available(*, deprecated)
    func updateAzureNodePool(
      request: UpdateAzureNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AzureClustersClient.updateAzureNodePool`.
    @available(*, deprecated)
    func updateAzureNodePoolPollingUntilDone(
      request: UpdateAzureNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> AzureNodePool

    /// See `AzureClustersClient.getAzureNodePool`.
    @available(*, deprecated)
    func getAzureNodePool(
      request: GetAzureNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AzureNodePool

    /// See `AzureClustersClient.listAzureNodePools`.
    @available(*, deprecated)
    func listAzureNodePools(
      request: ListAzureNodePoolsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureNodePoolsResponse

    /// See `AzureClustersClient.deleteAzureNodePool`.
    @available(*, deprecated)
    func deleteAzureNodePool(
      request: DeleteAzureNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AzureClustersClient.deleteAzureNodePool`.
    @available(*, deprecated)
    func deleteAzureNodePoolPollingUntilDone(
      request: DeleteAzureNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AzureClustersClient.getAzureOpenIdConfig`.
    @available(*, deprecated)
    func getAzureOpenIdConfig(
      request: GetAzureOpenIdConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AzureOpenIdConfig

    /// See `AzureClustersClient.getAzureJsonWebKeys`.
    @available(*, deprecated)
    func getAzureJsonWebKeys(
      request: GetAzureJsonWebKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AzureJsonWebKeys

    /// See `AzureClustersClient.getAzureServerConfig`.
    @available(*, deprecated)
    func getAzureServerConfig(
      request: GetAzureServerConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AzureServerConfig

    /// See `AzureClustersClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AzureClustersClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AzureClustersClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
@available(*, deprecated)
extension Clients.AzureClustersProtocol {
  @available(*, deprecated)
  public func createAzureClient(request: CreateAzureClientRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAzureClient(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createAzureClient(
    request: CreateAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAzureClientPollingUntilDone(request: CreateAzureClientRequest) async throws
    -> AzureClient
  {
    return try await self.createAzureClientPollingUntilDone(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createAzureClientPollingUntilDone(
    request: CreateAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureClient {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAzureClientPollingUntilDone(
    parent: Swift.String,
    azureClient: AzureClient?,
    azureClientId: Swift.String,
  ) async throws -> AzureClient {
    let request = CreateAzureClientRequest().with {
      $0.parent = parent
      $0.azureClient = azureClient
      $0.azureClientId = azureClientId
    }
    return try await self.createAzureClientPollingUntilDone(request: request)
  }

  @available(*, deprecated)
  public func getAzureClient(request: GetAzureClientRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AzureClient
  {
    try await self.getAzureClient(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAzureClient(
    request: GetAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureClient {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAzureClient(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureClient {
    let request = GetAzureClientRequest().with {
      $0.name = name
    }
    return try await self.getAzureClient(request: request)
  }

  @available(*, deprecated)
  public func listAzureClients(request: ListAzureClientsRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.ListAzureClientsResponse
  {
    try await self.listAzureClients(request: request, options: .init())
  }

  @available(*, deprecated)
  public func listAzureClients(
    request: ListAzureClientsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureClientsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func listAzureClientsByItems(
    request: ListAzureClientsRequest
  ) -> some AsyncSequence<AzureClient, Swift.Error> & Sendable {
    self.listAzureClientsByItems(request: request, options: .init())
  }

  /// Lists all [AzureClient][google.cloud.gkemulticloud.v1.AzureClient]
  /// resources on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  ///
  /// @Snippet(path: "AzureClusters_ListAzureClients")
  @available(*, deprecated)
  public func listAzureClientsByItems(
    request: ListAzureClientsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AzureClient, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudGKEMultiCloudV1.ListAzureClientsResponse in
      var request = request
      request.pageToken = token
      return try await self.listAzureClients(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  @available(*, deprecated)
  public func listAzureClientsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<AzureClient, Swift.Error> & Sendable {
    let request = ListAzureClientsRequest().with {
      $0.parent = parent
    }
    return self.listAzureClientsByItems(request: request)
  }

  @available(*, deprecated)
  public func deleteAzureClient(request: DeleteAzureClientRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAzureClient(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteAzureClient(
    request: DeleteAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteAzureClientPollingUntilDone(request: DeleteAzureClientRequest) async throws {
    try await self.deleteAzureClientPollingUntilDone(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteAzureClientPollingUntilDone(
    request: DeleteAzureClientRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteAzureClientPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteAzureClientRequest().with {
      $0.name = name
    }
    try await self.deleteAzureClientPollingUntilDone(request: request)
  }

  @available(*, deprecated)
  public func createAzureCluster(request: CreateAzureClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAzureCluster(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createAzureCluster(
    request: CreateAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAzureClusterPollingUntilDone(request: CreateAzureClusterRequest) async throws
    -> AzureCluster
  {
    return try await self.createAzureClusterPollingUntilDone(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createAzureClusterPollingUntilDone(
    request: CreateAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureCluster {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAzureClusterPollingUntilDone(
    parent: Swift.String,
    azureCluster: AzureCluster?,
    azureClusterId: Swift.String,
  ) async throws -> AzureCluster {
    let request = CreateAzureClusterRequest().with {
      $0.parent = parent
      $0.azureCluster = azureCluster
      $0.azureClusterId = azureClusterId
    }
    return try await self.createAzureClusterPollingUntilDone(request: request)
  }

  @available(*, deprecated)
  public func updateAzureCluster(request: UpdateAzureClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAzureCluster(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateAzureCluster(
    request: UpdateAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateAzureClusterPollingUntilDone(request: UpdateAzureClusterRequest) async throws
    -> AzureCluster
  {
    return try await self.updateAzureClusterPollingUntilDone(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateAzureClusterPollingUntilDone(
    request: UpdateAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureCluster {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateAzureClusterPollingUntilDone(
    azureCluster: AzureCluster?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> AzureCluster {
    let request = UpdateAzureClusterRequest().with {
      $0.azureCluster = azureCluster
      $0.updateMask = updateMask
    }
    return try await self.updateAzureClusterPollingUntilDone(request: request)
  }

  @available(*, deprecated)
  public func getAzureCluster(request: GetAzureClusterRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AzureCluster
  {
    try await self.getAzureCluster(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAzureCluster(
    request: GetAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureCluster {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAzureCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureCluster {
    let request = GetAzureClusterRequest().with {
      $0.name = name
    }
    return try await self.getAzureCluster(request: request)
  }

  @available(*, deprecated)
  public func listAzureClusters(request: ListAzureClustersRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.ListAzureClustersResponse
  {
    try await self.listAzureClusters(request: request, options: .init())
  }

  @available(*, deprecated)
  public func listAzureClusters(
    request: ListAzureClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureClustersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func listAzureClustersByItems(
    request: ListAzureClustersRequest
  ) -> some AsyncSequence<AzureCluster, Swift.Error> & Sendable {
    self.listAzureClustersByItems(request: request, options: .init())
  }

  /// Lists all [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster]
  /// resources on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  ///
  /// @Snippet(path: "AzureClusters_ListAzureClusters")
  @available(*, deprecated)
  public func listAzureClustersByItems(
    request: ListAzureClustersRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AzureCluster, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudGKEMultiCloudV1.ListAzureClustersResponse in
      var request = request
      request.pageToken = token
      return try await self.listAzureClusters(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  @available(*, deprecated)
  public func listAzureClustersByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<AzureCluster, Swift.Error> & Sendable {
    let request = ListAzureClustersRequest().with {
      $0.parent = parent
    }
    return self.listAzureClustersByItems(request: request)
  }

  @available(*, deprecated)
  public func deleteAzureCluster(request: DeleteAzureClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAzureCluster(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteAzureCluster(
    request: DeleteAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteAzureClusterPollingUntilDone(request: DeleteAzureClusterRequest) async throws {
    try await self.deleteAzureClusterPollingUntilDone(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteAzureClusterPollingUntilDone(
    request: DeleteAzureClusterRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteAzureClusterPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteAzureClusterRequest().with {
      $0.name = name
    }
    try await self.deleteAzureClusterPollingUntilDone(request: request)
  }

  @available(*, deprecated)
  public func generateAzureClusterAgentToken(request: GenerateAzureClusterAgentTokenRequest)
    async throws -> GoogleCloudGKEMultiCloudV1.GenerateAzureClusterAgentTokenResponse
  {
    try await self.generateAzureClusterAgentToken(request: request, options: .init())
  }

  @available(*, deprecated)
  public func generateAzureClusterAgentToken(
    request: GenerateAzureClusterAgentTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAzureClusterAgentTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func generateAzureAccessToken(request: GenerateAzureAccessTokenRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.GenerateAzureAccessTokenResponse
  {
    try await self.generateAzureAccessToken(request: request, options: .init())
  }

  @available(*, deprecated)
  public func generateAzureAccessToken(
    request: GenerateAzureAccessTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAzureAccessTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAzureNodePool(request: CreateAzureNodePoolRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAzureNodePool(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createAzureNodePool(
    request: CreateAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAzureNodePoolPollingUntilDone(request: CreateAzureNodePoolRequest) async throws
    -> AzureNodePool
  {
    return try await self.createAzureNodePoolPollingUntilDone(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createAzureNodePoolPollingUntilDone(
    request: CreateAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureNodePool {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAzureNodePoolPollingUntilDone(
    parent: Swift.String,
    azureNodePool: AzureNodePool?,
    azureNodePoolId: Swift.String,
  ) async throws -> AzureNodePool {
    let request = CreateAzureNodePoolRequest().with {
      $0.parent = parent
      $0.azureNodePool = azureNodePool
      $0.azureNodePoolId = azureNodePoolId
    }
    return try await self.createAzureNodePoolPollingUntilDone(request: request)
  }

  @available(*, deprecated)
  public func updateAzureNodePool(request: UpdateAzureNodePoolRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAzureNodePool(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateAzureNodePool(
    request: UpdateAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateAzureNodePoolPollingUntilDone(request: UpdateAzureNodePoolRequest) async throws
    -> AzureNodePool
  {
    return try await self.updateAzureNodePoolPollingUntilDone(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateAzureNodePoolPollingUntilDone(
    request: UpdateAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> AzureNodePool {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateAzureNodePoolPollingUntilDone(
    azureNodePool: AzureNodePool?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> AzureNodePool {
    let request = UpdateAzureNodePoolRequest().with {
      $0.azureNodePool = azureNodePool
      $0.updateMask = updateMask
    }
    return try await self.updateAzureNodePoolPollingUntilDone(request: request)
  }

  @available(*, deprecated)
  public func getAzureNodePool(request: GetAzureNodePoolRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AzureNodePool
  {
    try await self.getAzureNodePool(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAzureNodePool(
    request: GetAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureNodePool {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAzureNodePool(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureNodePool {
    let request = GetAzureNodePoolRequest().with {
      $0.name = name
    }
    return try await self.getAzureNodePool(request: request)
  }

  @available(*, deprecated)
  public func listAzureNodePools(request: ListAzureNodePoolsRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.ListAzureNodePoolsResponse
  {
    try await self.listAzureNodePools(request: request, options: .init())
  }

  @available(*, deprecated)
  public func listAzureNodePools(
    request: ListAzureNodePoolsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAzureNodePoolsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func listAzureNodePoolsByItems(
    request: ListAzureNodePoolsRequest
  ) -> some AsyncSequence<AzureNodePool, Swift.Error> & Sendable {
    self.listAzureNodePoolsByItems(request: request, options: .init())
  }

  /// Lists all [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool]
  /// resources on a given
  /// [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  ///
  /// @Snippet(path: "AzureClusters_ListAzureNodePools")
  @available(*, deprecated)
  public func listAzureNodePoolsByItems(
    request: ListAzureNodePoolsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AzureNodePool, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudGKEMultiCloudV1.ListAzureNodePoolsResponse in
      var request = request
      request.pageToken = token
      return try await self.listAzureNodePools(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  @available(*, deprecated)
  public func listAzureNodePoolsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<AzureNodePool, Swift.Error> & Sendable {
    let request = ListAzureNodePoolsRequest().with {
      $0.parent = parent
    }
    return self.listAzureNodePoolsByItems(request: request)
  }

  @available(*, deprecated)
  public func deleteAzureNodePool(request: DeleteAzureNodePoolRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAzureNodePool(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteAzureNodePool(
    request: DeleteAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteAzureNodePoolPollingUntilDone(request: DeleteAzureNodePoolRequest) async throws
  {
    try await self.deleteAzureNodePoolPollingUntilDone(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteAzureNodePoolPollingUntilDone(
    request: DeleteAzureNodePoolRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteAzureNodePoolPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteAzureNodePoolRequest().with {
      $0.name = name
    }
    try await self.deleteAzureNodePoolPollingUntilDone(request: request)
  }

  @available(*, deprecated)
  public func getAzureOpenIdConfig(request: GetAzureOpenIdConfigRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AzureOpenIdConfig
  {
    try await self.getAzureOpenIdConfig(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAzureOpenIdConfig(
    request: GetAzureOpenIdConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureOpenIdConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAzureOpenIdConfig(
    azureCluster: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureOpenIdConfig {
    let request = GetAzureOpenIdConfigRequest().with {
      $0.azureCluster = azureCluster
    }
    return try await self.getAzureOpenIdConfig(request: request)
  }

  @available(*, deprecated)
  public func getAzureJsonWebKeys(request: GetAzureJsonWebKeysRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AzureJsonWebKeys
  {
    try await self.getAzureJsonWebKeys(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAzureJsonWebKeys(
    request: GetAzureJsonWebKeysRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureJsonWebKeys {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAzureJsonWebKeys(
    azureCluster: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureJsonWebKeys {
    let request = GetAzureJsonWebKeysRequest().with {
      $0.azureCluster = azureCluster
    }
    return try await self.getAzureJsonWebKeys(request: request)
  }

  @available(*, deprecated)
  public func getAzureServerConfig(request: GetAzureServerConfigRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AzureServerConfig
  {
    try await self.getAzureServerConfig(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAzureServerConfig(
    request: GetAzureServerConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureServerConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAzureServerConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AzureServerConfig {
    let request = GetAzureServerConfigRequest().with {
      $0.name = name
    }
    return try await self.getAzureServerConfig(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AzureClusters_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
