// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AzureOpenIdConfig is an OIDC discovery document for the cluster.
/// See the OpenID Connect Discovery 1.0 specification for details.
@available(*, deprecated)
public struct AzureOpenIdConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// OIDC Issuer.
  public var issuer: Swift.String = Swift.String()

  /// JSON Web Key uri.
  public var jwksUri: Swift.String = Swift.String()

  /// Supported response types.
  public var responseTypesSupported: [Swift.String] = []

  /// Supported subject types.
  public var subjectTypesSupported: [Swift.String] = []

  /// supported ID Token signing Algorithms.
  public var idTokenSigningAlgValuesSupported: [Swift.String] = []

  /// Supported claims.
  public var claimsSupported: [Swift.String] = []

  /// Supported grant types.
  public var grantTypes: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AzureOpenIdConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureOpenIdConfig().with { $0.issuer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let issuer = CodingKeys(stringValue: "issuer")
    static let jwksUri = CodingKeys(stringValue: "jwks_uri")
    static let responseTypesSupported = CodingKeys(stringValue: "response_types_supported")
    static let subjectTypesSupported = CodingKeys(stringValue: "subject_types_supported")
    static let idTokenSigningAlgValuesSupported = CodingKeys(
      stringValue: "id_token_signing_alg_values_supported")
    static let claimsSupported = CodingKeys(stringValue: "claims_supported")
    static let grantTypes = CodingKeys(stringValue: "grant_types")

    static let _knownKeys: Set<Swift.String> = [
      "issuer",
      "jwks_uri",
      "response_types_supported",
      "subject_types_supported",
      "id_token_signing_alg_values_supported",
      "claims_supported",
      "grant_types",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .issuer) {
      self.issuer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jwksUri) {
      self.jwksUri = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .responseTypesSupported)
    {
      self.responseTypesSupported = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .subjectTypesSupported)
    {
      self.subjectTypesSupported = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .idTokenSigningAlgValuesSupported)
    {
      self.idTokenSigningAlgValuesSupported = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .claimsSupported) {
      self.claimsSupported = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .grantTypes) {
      self.grantTypes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.issuer, forKey: .issuer)
    try container.encode(self.jwksUri, forKey: .jwksUri)
    try container.encode(self.responseTypesSupported, forKey: .responseTypesSupported)
    try container.encode(self.subjectTypesSupported, forKey: .subjectTypesSupported)
    try container.encode(
      self.idTokenSigningAlgValuesSupported, forKey: .idTokenSigningAlgValuesSupported)
    try container.encode(self.claimsSupported, forKey: .claimsSupported)
    try container.encode(self.grantTypes, forKey: .grantTypes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AzureOpenIdConfig`: `"type.googleapis.com/google.cloud.gkemulticloud.v1.AzureOpenIdConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureOpenIdConfig"
  }

  /// Initialize an instance of `AzureOpenIdConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkemulticloud.v1.AzureOpenIdConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AzureOpenIdConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
