// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AzureControlPlane represents the control plane configurations.
@available(*, deprecated)
public struct AzureControlPlane: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The Kubernetes version to run on control plane replicas
  /// (e.g. `1.19.10-gke.1000`).
  ///
  /// You can list all supported versions on a given Google Cloud region by
  /// calling
  /// [GetAzureServerConfig][google.cloud.gkemulticloud.v1.AzureClusters.GetAzureServerConfig].
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClusters.GetAzureServerConfig]: <doc:AzureClustersClient/getAzureServerConfig(request:options:)>
  public var version: Swift.String = Swift.String()

  /// Optional. The ARM ID of the default subnet for the control plane. The
  /// control plane VMs are deployed in this subnet, unless
  /// `AzureControlPlane.replica_placements` is specified. This subnet will also
  /// be used as default for `AzureControlPlane.endpoint_subnet_id` if
  /// `AzureControlPlane.endpoint_subnet_id` is not specified. Similarly it will
  /// be used as default for
  /// `AzureClusterNetworking.service_load_balancer_subnet_id`.
  ///
  /// Example:
  /// `/subscriptions/<subscription-id>/resourceGroups/<resource-group-id>/providers/Microsoft.Network/virtualNetworks/<vnet-id>/subnets/default`.
  public var subnetId: Swift.String = Swift.String()

  /// Optional. The Azure VM size name. Example: `Standard_DS2_v2`.
  ///
  /// For available VM sizes, see
  /// https://docs.microsoft.com/en-us/azure/virtual-machines/vm-naming-conventions.
  ///
  /// When unspecified, it defaults to `Standard_DS2_v2`.
  public var vmSize: Swift.String = Swift.String()

  /// Required. SSH configuration for how to access the underlying control plane
  /// machines.
  public var sshConfig: AzureSshConfig? = nil

  /// Optional. Configuration related to the root volume provisioned for each
  /// control plane replica.
  ///
  /// When unspecified, it defaults to 32-GiB Azure Disk.
  public var rootVolume: AzureDiskTemplate? = nil

  /// Optional. Configuration related to the main volume provisioned for each
  /// control plane replica.
  /// The main volume is in charge of storing all of the cluster's etcd state.
  ///
  /// When unspecified, it defaults to a 8-GiB Azure Disk.
  public var mainVolume: AzureDiskTemplate? = nil

  /// Optional. Configuration related to application-layer secrets encryption.
  public var databaseEncryption: AzureDatabaseEncryption? = nil

  /// Optional. Proxy configuration for outbound HTTP(S) traffic.
  public var proxyConfig: AzureProxyConfig? = nil

  /// Optional. Configuration related to vm config encryption.
  public var configEncryption: AzureConfigEncryption? = nil

  /// Optional. A set of tags to apply to all underlying control plane Azure
  /// resources.
  public var tags: [Swift.String: Swift.String] = [:]

  /// Optional. Configuration for where to place the control plane replicas.
  ///
  /// Up to three replica placement instances can be specified. If
  /// replica_placements is set, the replica placement instances will be applied
  /// to the three control plane replicas as evenly as possible.
  public var replicaPlacements: [ReplicaPlacement] = []

  /// Optional. The ARM ID of the subnet where the control plane load balancer is
  /// deployed. When unspecified, it defaults to AzureControlPlane.subnet_id.
  ///
  /// Example:
  /// "/subscriptions/d00494d6-6f3c-4280-bbb2-899e163d1d30/resourceGroups/anthos_cluster_gkeust4/providers/Microsoft.Network/virtualNetworks/gke-vnet-gkeust4/subnets/subnetid123"
  public var endpointSubnetId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AzureControlPlane`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureControlPlane().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let version = CodingKeys(stringValue: "version")
    static let subnetId = CodingKeys(stringValue: "subnetId")
    static let vmSize = CodingKeys(stringValue: "vmSize")
    static let sshConfig = CodingKeys(stringValue: "sshConfig")
    static let rootVolume = CodingKeys(stringValue: "rootVolume")
    static let mainVolume = CodingKeys(stringValue: "mainVolume")
    static let databaseEncryption = CodingKeys(stringValue: "databaseEncryption")
    static let proxyConfig = CodingKeys(stringValue: "proxyConfig")
    static let configEncryption = CodingKeys(stringValue: "configEncryption")
    static let tags = CodingKeys(stringValue: "tags")
    static let replicaPlacements = CodingKeys(stringValue: "replicaPlacements")
    static let endpointSubnetId = CodingKeys(stringValue: "endpointSubnetId")

    static let _knownKeys: Set<Swift.String> = [
      "version",
      "subnetId",
      "vmSize",
      "sshConfig",
      "rootVolume",
      "mainVolume",
      "databaseEncryption",
      "proxyConfig",
      "configEncryption",
      "tags",
      "replicaPlacements",
      "endpointSubnetId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetId) {
      self.subnetId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmSize) {
      self.vmSize = value
    }
    self.sshConfig = try container.decodeIfPresent(AzureSshConfig.self, forKey: .sshConfig)
    self.rootVolume = try container.decodeIfPresent(AzureDiskTemplate.self, forKey: .rootVolume)
    self.mainVolume = try container.decodeIfPresent(AzureDiskTemplate.self, forKey: .mainVolume)
    self.databaseEncryption = try container.decodeIfPresent(
      AzureDatabaseEncryption.self, forKey: .databaseEncryption)
    self.proxyConfig = try container.decodeIfPresent(AzureProxyConfig.self, forKey: .proxyConfig)
    self.configEncryption = try container.decodeIfPresent(
      AzureConfigEncryption.self, forKey: .configEncryption)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent(
      [ReplicaPlacement].self, forKey: .replicaPlacements)
    {
      self.replicaPlacements = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .endpointSubnetId) {
      self.endpointSubnetId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.subnetId, forKey: .subnetId)
    try container.encode(self.vmSize, forKey: .vmSize)
    try container.encodeIfPresent(self.sshConfig, forKey: .sshConfig)
    try container.encodeIfPresent(self.rootVolume, forKey: .rootVolume)
    try container.encodeIfPresent(self.mainVolume, forKey: .mainVolume)
    try container.encodeIfPresent(self.databaseEncryption, forKey: .databaseEncryption)
    try container.encodeIfPresent(self.proxyConfig, forKey: .proxyConfig)
    try container.encodeIfPresent(self.configEncryption, forKey: .configEncryption)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.replicaPlacements, forKey: .replicaPlacements)
    try container.encode(self.endpointSubnetId, forKey: .endpointSubnetId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AzureControlPlane`: `"type.googleapis.com/google.cloud.gkemulticloud.v1.AzureControlPlane"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureControlPlane"
  }

  /// Initialize an instance of `AzureControlPlane` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkemulticloud.v1.AzureControlPlane"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AzureControlPlane` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
