// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An Anthos node pool running on Azure.
@available(*, deprecated)
public struct AzureNodePool: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of this resource.
  ///
  /// Node pool names are formatted as
  /// `projects/<project-number>/locations/<region>/azureClusters/<cluster-id>/azureNodePools/<node-pool-id>`.
  ///
  /// For more details on Google Cloud resource names,
  /// see [Resource Names](https://cloud.google.com/apis/design/resource_names)
  public var name: Swift.String = Swift.String()

  /// Required. The Kubernetes version (e.g. `1.19.10-gke.1000`) running on this
  /// node pool.
  public var version: Swift.String = Swift.String()

  /// Required. The node configuration of the node pool.
  public var config: AzureNodeConfig? = nil

  /// Required. The ARM ID of the subnet where the node pool VMs run. Make sure
  /// it's a subnet under the virtual network in the cluster configuration.
  public var subnetId: Swift.String = Swift.String()

  /// Required. Autoscaler configuration for this node pool.
  public var autoscaling: AzureNodePoolAutoscaling? = nil

  /// Output only. The current state of the node pool.
  public var state: AzureNodePool.State = AzureNodePool.State()

  /// Output only. A globally unique identifier for the node pool.
  public var uid: Swift.String = Swift.String()

  /// Output only. If set, there are currently pending changes to the node
  /// pool.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Output only. The time at which this node pool was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which this node pool was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Allows clients to perform consistent read-modify-writes
  /// through optimistic concurrency control.
  ///
  /// Can be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. Annotations on the node pool.
  ///
  /// This field has the same restrictions as Kubernetes annotations.
  /// The total size of all keys and values combined is limited to 256k.
  /// Keys can have 2 segments: prefix (optional) and name (required),
  /// separated by a slash (/).
  /// Prefix must be a DNS subdomain.
  /// Name must be 63 characters or less, begin and end with alphanumerics,
  /// with dashes (-), underscores (_), dots (.), and alphanumerics between.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Required. The constraint on the maximum number of pods that can be run
  /// simultaneously on a node in the node pool.
  public var maxPodsConstraint: MaxPodsConstraint? = nil

  /// Optional. The Azure availability zone of the nodes in this nodepool.
  ///
  /// When unspecified, it defaults to `1`.
  public var azureAvailabilityZone: Swift.String = Swift.String()

  /// Output only. A set of errors found in the node pool.
  public var errors: [AzureNodePoolError] = []

  /// Optional. The Management configuration for this node pool.
  public var management: AzureNodeManagement? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AzureNodePool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureNodePool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let version = CodingKeys(stringValue: "version")
    static let config = CodingKeys(stringValue: "config")
    static let subnetId = CodingKeys(stringValue: "subnetId")
    static let autoscaling = CodingKeys(stringValue: "autoscaling")
    static let state = CodingKeys(stringValue: "state")
    static let uid = CodingKeys(stringValue: "uid")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let maxPodsConstraint = CodingKeys(stringValue: "maxPodsConstraint")
    static let azureAvailabilityZone = CodingKeys(stringValue: "azureAvailabilityZone")
    static let errors = CodingKeys(stringValue: "errors")
    static let management = CodingKeys(stringValue: "management")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "version",
      "config",
      "subnetId",
      "autoscaling",
      "state",
      "uid",
      "reconciling",
      "createTime",
      "updateTime",
      "etag",
      "annotations",
      "maxPodsConstraint",
      "azureAvailabilityZone",
      "errors",
      "management",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    self.config = try container.decodeIfPresent(AzureNodeConfig.self, forKey: .config)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetId) {
      self.subnetId = value
    }
    self.autoscaling = try container.decodeIfPresent(
      AzureNodePoolAutoscaling.self, forKey: .autoscaling)
    if let value = try container.decodeIfPresent(AzureNodePool.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    self.maxPodsConstraint = try container.decodeIfPresent(
      MaxPodsConstraint.self, forKey: .maxPodsConstraint)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .azureAvailabilityZone)
    {
      self.azureAvailabilityZone = value
    }
    if let value = try container.decodeIfPresent([AzureNodePoolError].self, forKey: .errors) {
      self.errors = value
    }
    self.management = try container.decodeIfPresent(AzureNodeManagement.self, forKey: .management)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.version, forKey: .version)
    try container.encodeIfPresent(self.config, forKey: .config)
    try container.encode(self.subnetId, forKey: .subnetId)
    try container.encodeIfPresent(self.autoscaling, forKey: .autoscaling)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encodeIfPresent(self.maxPodsConstraint, forKey: .maxPodsConstraint)
    try container.encode(self.azureAvailabilityZone, forKey: .azureAvailabilityZone)
    try container.encode(self.errors, forKey: .errors)
    try container.encodeIfPresent(self.management, forKey: .management)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The lifecycle state of the node pool.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Not set.
    case unspecified
    /// The PROVISIONING state indicates the node pool is being created.
    case provisioning
    /// The RUNNING state indicates the node pool has been created and is fully
    /// usable.
    case running
    /// The RECONCILING state indicates that the node pool is being reconciled.
    case reconciling
    /// The STOPPING state indicates the node pool is being deleted.
    case stopping
    /// The ERROR state indicates the node pool is in a broken unrecoverable
    /// state.
    case error
    /// The DEGRADED state indicates the node pool requires user action to
    /// restore full functionality.
    case degraded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .running: return 2
      case .reconciling: return 3
      case .stopping: return 4
      case .error: return 5
      case .degraded: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .running: return "RUNNING"
      case .reconciling: return "RECONCILING"
      case .stopping: return "STOPPING"
      case .error: return "ERROR"
      case .degraded: return "DEGRADED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "RUNNING": self = .running
      case "RECONCILING": self = .reconciling
      case "STOPPING": self = .stopping
      case "ERROR": self = .error
      case "DEGRADED": self = .degraded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .running
      case 3: self = .reconciling
      case 4: self = .stopping
      case 5: self = .error
      case 6: self = .degraded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .provisioning: return try container.encode("PROVISIONING")
      case .running: return try container.encode("RUNNING")
      case .reconciling: return try container.encode("RECONCILING")
      case .stopping: return try container.encode("STOPPING")
      case .error: return try container.encode("ERROR")
      case .degraded: return try container.encode("DEGRADED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `AzureNodePool`: `"type.googleapis.com/google.cloud.gkemulticloud.v1.AzureNodePool"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureNodePool"
  }

  /// Initialize an instance of `AzureNodePool` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkemulticloud.v1.AzureNodePool"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AzureNodePool` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
