// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ClusterNetworking contains cluster-wide networking configuration.
@available(*, deprecated)
public struct AzureClusterNetworking: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The Azure Resource Manager (ARM) ID of the VNet associated with
  /// your cluster.
  ///
  /// All components in the cluster (i.e. control plane and node pools) run on a
  /// single VNet.
  ///
  /// Example:
  /// `/subscriptions/<subscription-id>/resourceGroups/<resource-group-id>/providers/Microsoft.Network/virtualNetworks/<vnet-id>`
  ///
  /// This field cannot be changed after creation.
  public var virtualNetworkId: Swift.String = Swift.String()

  /// Required. The IP address range of the pods in this cluster, in CIDR
  /// notation (e.g. `10.96.0.0/14`).
  ///
  /// All pods in the cluster get assigned a unique IPv4 address from these
  /// ranges. Only a single range is supported.
  ///
  /// This field cannot be changed after creation.
  public var podAddressCidrBlocks: [Swift.String] = []

  /// Required. The IP address range for services in this cluster, in CIDR
  /// notation (e.g. `10.96.0.0/14`).
  ///
  /// All services in the cluster get assigned a unique IPv4 address from these
  /// ranges. Only a single range is supported.
  ///
  /// This field cannot be changed after creating a cluster.
  public var serviceAddressCidrBlocks: [Swift.String] = []

  /// Optional. The ARM ID of the subnet where Kubernetes private service type
  /// load balancers are deployed. When unspecified, it defaults to
  /// AzureControlPlane.subnet_id.
  ///
  /// Example:
  /// "/subscriptions/d00494d6-6f3c-4280-bbb2-899e163d1d30/resourceGroups/anthos_cluster_gkeust4/providers/Microsoft.Network/virtualNetworks/gke-vnet-gkeust4/subnets/subnetid456"
  public var serviceLoadBalancerSubnetId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AzureClusterNetworking`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureClusterNetworking().with { $0.virtualNetworkId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let virtualNetworkId = CodingKeys(stringValue: "virtualNetworkId")
    static let podAddressCidrBlocks = CodingKeys(stringValue: "podAddressCidrBlocks")
    static let serviceAddressCidrBlocks = CodingKeys(stringValue: "serviceAddressCidrBlocks")
    static let serviceLoadBalancerSubnetId = CodingKeys(stringValue: "serviceLoadBalancerSubnetId")

    static let _knownKeys: Set<Swift.String> = [
      "virtualNetworkId",
      "podAddressCidrBlocks",
      "serviceAddressCidrBlocks",
      "serviceLoadBalancerSubnetId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .virtualNetworkId) {
      self.virtualNetworkId = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .podAddressCidrBlocks)
    {
      self.podAddressCidrBlocks = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .serviceAddressCidrBlocks)
    {
      self.serviceAddressCidrBlocks = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .serviceLoadBalancerSubnetId)
    {
      self.serviceLoadBalancerSubnetId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.virtualNetworkId, forKey: .virtualNetworkId)
    try container.encode(self.podAddressCidrBlocks, forKey: .podAddressCidrBlocks)
    try container.encode(self.serviceAddressCidrBlocks, forKey: .serviceAddressCidrBlocks)
    try container.encode(self.serviceLoadBalancerSubnetId, forKey: .serviceLoadBalancerSubnetId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureClusterNetworking"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
