// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details of a proxy config stored in Azure Key Vault.
@available(*, deprecated)
public struct AzureProxyConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The ARM ID the of the resource group containing proxy keyvault.
  ///
  /// Resource group ids are formatted as
  /// `/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>`.
  public var resourceGroupId: Swift.String = Swift.String()

  /// The URL the of the proxy setting secret with its version.
  ///
  /// The secret must be a JSON encoded proxy configuration
  /// as described in
  /// https://cloud.google.com/kubernetes-engine/multi-cloud/docs/azure/how-to/use-a-proxy#create_a_proxy_configuration_file
  ///
  /// Secret ids are formatted as
  /// `https://<key-vault-name>.vault.azure.net/secrets/<secret-name>/<secret-version>`.
  public var secretId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AzureProxyConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureProxyConfig().with { $0.resourceGroupId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resourceGroupId = CodingKeys(stringValue: "resourceGroupId")
    static let secretId = CodingKeys(stringValue: "secretId")

    static let _knownKeys: Set<Swift.String> = [
      "resourceGroupId",
      "secretId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceGroupId) {
      self.resourceGroupId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secretId) {
      self.secretId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.resourceGroupId, forKey: .resourceGroupId)
    try container.encode(self.secretId, forKey: .secretId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureProxyConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
