// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for `AzureClusters.CreateAzureNodePool` method.
@available(*, deprecated)
public struct CreateAzureNodePoolRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster]
  /// resource where this node pool will be created.
  ///
  /// `AzureCluster` names are formatted as
  /// `projects/<project-id>/locations/<region>/azureClusters/<cluster-id>`.
  ///
  /// See [Resource Names](https://cloud.google.com/apis/design/resource_names)
  /// for more details on Google Cloud resource names.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
  public var parent: Swift.String = Swift.String()

  /// Required. The specification of the
  /// [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool] to create.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  public var azureNodePool: AzureNodePool? = nil

  /// Required. A client provided ID the resource. Must be unique within the
  /// parent resource.
  ///
  /// The provided ID will be part of the
  /// [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool] resource name
  /// formatted as
  /// `projects/<project-id>/locations/<region>/azureClusters/<cluster-id>/azureNodePools/<node-pool-id>`.
  ///
  /// Valid characters are `/[a-z][0-9]-/`. Cannot be longer than 63 characters.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  public var azureNodePoolId: Swift.String = Swift.String()

  /// If set, only validate the request, but do not actually create the node
  /// pool.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateAzureNodePoolRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAzureNodePoolRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let azureNodePool = CodingKeys(stringValue: "azureNodePool")
    static let azureNodePoolId = CodingKeys(stringValue: "azureNodePoolId")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "azureNodePool",
      "azureNodePoolId",
      "validateOnly",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.azureNodePool = try container.decodeIfPresent(AzureNodePool.self, forKey: .azureNodePool)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .azureNodePoolId) {
      self.azureNodePoolId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.azureNodePool, forKey: .azureNodePool)
    try container.encode(self.azureNodePoolId, forKey: .azureNodePoolId)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.CreateAzureNodePoolRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
