// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for `AwsClusters.DeleteAwsNodePool` method.
@available(*, deprecated)
public struct DeleteAwsNodePoolRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name the
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool] to delete.
  ///
  /// `AwsNodePool` names are formatted as
  /// `projects/<project-id>/locations/<region>/awsClusters/<cluster-id>/awsNodePools/<node-pool-id>`.
  ///
  /// See [Resource Names](https://cloud.google.com/apis/design/resource_names)
  /// for more details on Google Cloud resource names.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  public var name: Swift.String = Swift.String()

  /// If set, only validate the request, but do not actually delete the node
  /// pool.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// If set to true, and the
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool] resource is not
  /// found, the request will succeed but no action will be taken on the server
  /// and a completed [Operation][google.longrunning.Operation] will be returned.
  ///
  /// Useful for idempotent deletion.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Optional. If set to true, the deletion of
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool] resource will
  /// succeed even if errors occur during deleting in node pool resources. Using
  /// this parameter may result in orphaned resources in the node pool.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  public var ignoreErrors: Swift.Bool = Swift.Bool()

  /// The current ETag of the
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool].
  ///
  /// Allows clients to perform deletions through optimistic concurrency control.
  ///
  /// If the provided ETag does not match the current etag of the node pool,
  /// the request will fail and an ABORTED error will be returned.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DeleteAwsNodePoolRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteAwsNodePoolRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")
    static let allowMissing = CodingKeys(stringValue: "allowMissing")
    static let ignoreErrors = CodingKeys(stringValue: "ignoreErrors")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "validateOnly",
      "allowMissing",
      "ignoreErrors",
      "etag",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowMissing) {
      self.allowMissing = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .ignoreErrors) {
      self.ignoreErrors = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    try container.encode(self.allowMissing, forKey: .allowMissing)
    try container.encode(self.ignoreErrors, forKey: .ignoreErrors)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.DeleteAwsNodePoolRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
