// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Jwk is a JSON Web Key as specified in RFC 7517.
public struct Jwk: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Key Type.
  public var kty: Swift.String = Swift.String()

  /// Algorithm.
  public var alg: Swift.String = Swift.String()

  /// Permitted uses for the public keys.
  public var use: Swift.String = Swift.String()

  /// Key ID.
  public var kid: Swift.String = Swift.String()

  /// Used for RSA keys.
  public var n: Swift.String = Swift.String()

  /// Used for RSA keys.
  public var e: Swift.String = Swift.String()

  /// Used for ECDSA keys.
  public var x: Swift.String = Swift.String()

  /// Used for ECDSA keys.
  public var y: Swift.String = Swift.String()

  /// Used for ECDSA keys.
  public var crv: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Jwk`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Jwk().with { $0.kty = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let kty = CodingKeys(stringValue: "kty")
    static let alg = CodingKeys(stringValue: "alg")
    static let use = CodingKeys(stringValue: "use")
    static let kid = CodingKeys(stringValue: "kid")
    static let n = CodingKeys(stringValue: "n")
    static let e = CodingKeys(stringValue: "e")
    static let x = CodingKeys(stringValue: "x")
    static let y = CodingKeys(stringValue: "y")
    static let crv = CodingKeys(stringValue: "crv")

    static let _knownKeys: Set<Swift.String> = [
      "kty",
      "alg",
      "use",
      "kid",
      "n",
      "e",
      "x",
      "y",
      "crv",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kty) {
      self.kty = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .alg) {
      self.alg = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .use) {
      self.use = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kid) {
      self.kid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .n) {
      self.n = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .e) {
      self.e = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .x) {
      self.x = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .y) {
      self.y = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .crv) {
      self.crv = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.kty, forKey: .kty)
    try container.encode(self.alg, forKey: .alg)
    try container.encode(self.use, forKey: .use)
    try container.encode(self.kid, forKey: .kid)
    try container.encode(self.n, forKey: .n)
    try container.encode(self.e, forKey: .e)
    try container.encode(self.x, forKey: .x)
    try container.encode(self.y, forKey: .y)
    try container.encode(self.crv, forKey: .crv)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.Jwk"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
