// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Parameters that describe the Monitoring configuration in a cluster.
public struct MonitoringConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Enable Google Cloud Managed Service for Prometheus in the cluster.
  public var managedPrometheusConfig: ManagedPrometheusConfig? = nil

  /// Optionally enable GKE metrics.
  /// Only for Attached Clusters.
  public var cloudMonitoringConfig: CloudMonitoringConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MonitoringConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MonitoringConfig().with { $0.managedPrometheusConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let managedPrometheusConfig = CodingKeys(stringValue: "managedPrometheusConfig")
    static let cloudMonitoringConfig = CodingKeys(stringValue: "cloudMonitoringConfig")

    static let _knownKeys: Set<Swift.String> = [
      "managedPrometheusConfig",
      "cloudMonitoringConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.managedPrometheusConfig = try container.decodeIfPresent(
      ManagedPrometheusConfig.self, forKey: .managedPrometheusConfig)
    self.cloudMonitoringConfig = try container.decodeIfPresent(
      CloudMonitoringConfig.self, forKey: .cloudMonitoringConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.managedPrometheusConfig, forKey: .managedPrometheusConfig)
    try container.encodeIfPresent(self.cloudMonitoringConfig, forKey: .cloudMonitoringConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `MonitoringConfig`: `"type.googleapis.com/google.cloud.gkemulticloud.v1.MonitoringConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.MonitoringConfig"
  }

  /// Initialize an instance of `MonitoringConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkemulticloud.v1.MonitoringConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `MonitoringConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
