// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for node pool kubelet options.
public struct NodeKubeletConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Enable the insecure kubelet read only port.
  public var insecureKubeletReadonlyPortEnabled: Swift.Bool = Swift.Bool()

  /// Optional. Control the CPU management policy on the node.
  /// See
  /// https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/
  ///
  /// The following values are allowed.
  /// * "none": the default, which represents the existing scheduling behavior.
  /// * "static": allows pods with certain resource characteristics to be granted
  /// increased CPU affinity and exclusivity on the node.
  /// The default value is 'none' if unspecified.
  public var cpuManagerPolicy: Swift.String? = nil

  /// Optional. Enable CPU CFS quota enforcement for containers that specify CPU
  /// limits.
  ///
  /// This option is enabled by default which makes kubelet use CFS quota
  /// (https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt) to
  /// enforce container CPU limits. Otherwise, CPU limits will not be enforced at
  /// all.
  ///
  /// Disable this option to mitigate CPU throttling problems while still having
  /// your pods to be in Guaranteed QoS class by specifying the CPU limits.
  ///
  /// The default value is 'true' if unspecified.
  public var cpuCfsQuota: Swift.Bool? = nil

  /// Optional. Set the CPU CFS quota period value 'cpu.cfs_period_us'.
  ///
  /// The string must be a sequence of decimal numbers, each with optional
  /// fraction and a unit suffix, such as "300ms".
  /// Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  /// The value must be a positive duration.
  ///
  /// The default value is '100ms' if unspecified.
  public var cpuCfsQuotaPeriod: Swift.String? = nil

  /// Optional. Set the Pod PID limits. See
  /// https://kubernetes.io/docs/concepts/policy/pid-limiting/#pod-pid-limits
  ///
  /// Controls the maximum number of processes allowed to run in a pod. The value
  /// must be greater than or equal to 1024 and less than 4194304.
  public var podPidsLimit: Swift.Int64? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NodeKubeletConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NodeKubeletConfig().with { $0.insecureKubeletReadonlyPortEnabled = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let insecureKubeletReadonlyPortEnabled = CodingKeys(
      stringValue: "insecureKubeletReadonlyPortEnabled")
    static let cpuManagerPolicy = CodingKeys(stringValue: "cpuManagerPolicy")
    static let cpuCfsQuota = CodingKeys(stringValue: "cpuCfsQuota")
    static let cpuCfsQuotaPeriod = CodingKeys(stringValue: "cpuCfsQuotaPeriod")
    static let podPidsLimit = CodingKeys(stringValue: "podPidsLimit")

    static let _knownKeys: Set<Swift.String> = [
      "insecureKubeletReadonlyPortEnabled",
      "cpuManagerPolicy",
      "cpuCfsQuota",
      "cpuCfsQuotaPeriod",
      "podPidsLimit",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .insecureKubeletReadonlyPortEnabled)
    {
      self.insecureKubeletReadonlyPortEnabled = value
    }
    self.cpuManagerPolicy = try container.decodeIfPresent(
      Swift.String.self, forKey: .cpuManagerPolicy)
    self.cpuCfsQuota = try container.decodeIfPresent(Swift.Bool.self, forKey: .cpuCfsQuota)
    self.cpuCfsQuotaPeriod = try container.decodeIfPresent(
      Swift.String.self, forKey: .cpuCfsQuotaPeriod)
    self.podPidsLimit = try container.decodeIfPresent(Swift.Int64.self, forKey: .podPidsLimit)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(
      self.insecureKubeletReadonlyPortEnabled, forKey: .insecureKubeletReadonlyPortEnabled)
    try container.encodeIfPresent(self.cpuManagerPolicy, forKey: .cpuManagerPolicy)
    try container.encodeIfPresent(self.cpuCfsQuota, forKey: .cpuCfsQuota)
    try container.encodeIfPresent(self.cpuCfsQuotaPeriod, forKey: .cpuCfsQuotaPeriod)
    try container.encodeIfPresent(self.podPidsLimit, forKey: .podPidsLimit)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.NodeKubeletConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
