// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata about a long-running operation.
public struct OperationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The time at which this operation was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which this operation was completed.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The name of the resource associated to this operation.
  public var target: Swift.String = Swift.String()

  /// Output only. Human-readable status of the operation, if any.
  public var statusDetail: Swift.String = Swift.String()

  /// Output only. Human-readable status of any error that occurred during the
  /// operation.
  public var errorDetail: Swift.String = Swift.String()

  /// Output only. The verb associated with the API method which triggered this
  /// operation. Possible values are "create", "delete", "update" and "import".
  public var verb: Swift.String = Swift.String()

  /// Output only. Identifies whether cancellation has been requested for the
  /// operation. Operations that have successfully been cancelled have
  /// [google.longrunning.Operation.error][google.longrunning.Operation.error]
  /// value with a [google.rpc.Status.code][google.rpc.Status.code] of 1,
  /// corresponding to `Code.CANCELLED`.
  ///
  /// [google.longrunning.Operation.error]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/ResultOneOf/error(_:)
  /// [google.rpc.Status.code]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status/code
  public var requestedCancellation: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadata().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createTime = CodingKeys(stringValue: "createTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let target = CodingKeys(stringValue: "target")
    static let statusDetail = CodingKeys(stringValue: "statusDetail")
    static let errorDetail = CodingKeys(stringValue: "errorDetail")
    static let verb = CodingKeys(stringValue: "verb")
    static let requestedCancellation = CodingKeys(stringValue: "requestedCancellation")

    static let _knownKeys: Set<Swift.String> = [
      "createTime",
      "endTime",
      "target",
      "statusDetail",
      "errorDetail",
      "verb",
      "requestedCancellation",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .target) {
      self.target = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statusDetail) {
      self.statusDetail = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorDetail) {
      self.errorDetail = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .verb) {
      self.verb = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requestedCancellation) {
      self.requestedCancellation = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.target, forKey: .target)
    try container.encode(self.statusDetail, forKey: .statusDetail)
    try container.encode(self.errorDetail, forKey: .errorDetail)
    try container.encode(self.verb, forKey: .verb)
    try container.encode(self.requestedCancellation, forKey: .requestedCancellation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.OperationMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
