// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Toleration defines the fields for tolerations for pods created by
/// auto-installed components.
public struct Toleration: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Key is the taint key that the toleration applies to.
  public var key: Swift.String = Swift.String()

  /// Value is the taint value that the toleration applies to.
  public var value: Swift.String = Swift.String()

  /// KeyOperator represents a key's relationship to the value e.g. 'Exist'.
  public var keyOperator: Toleration.KeyOperator = Toleration.KeyOperator()

  /// Effect indicates the taint effect to match e.g. 'NoSchedule'
  public var effect: Toleration.Effect = Toleration.Effect()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Toleration`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Toleration().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let key = CodingKeys(stringValue: "key")
    static let value = CodingKeys(stringValue: "value")
    static let keyOperator = CodingKeys(stringValue: "keyOperator")
    static let effect = CodingKeys(stringValue: "effect")

    static let _knownKeys: Set<Swift.String> = [
      "key",
      "value",
      "keyOperator",
      "effect",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
      self.key = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .value) {
      self.value = value
    }
    if let value = try container.decodeIfPresent(Toleration.KeyOperator.self, forKey: .keyOperator)
    {
      self.keyOperator = value
    }
    if let value = try container.decodeIfPresent(Toleration.Effect.self, forKey: .effect) {
      self.effect = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.value, forKey: .value)
    try container.encode(self.keyOperator, forKey: .keyOperator)
    try container.encode(self.effect, forKey: .effect)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// KeyOperator represents a key's relationship to the value e.g. 'Equal'.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum KeyOperator: Codable, Equatable, Hashable, Sendable {
    /// Operator is not specified.
    case unspecified
    /// Operator maps to 'Equal'.
    case equal
    /// Operator maps to 'Exists'.
    case exists
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .equal: return 1
      case .exists: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "KEY_OPERATOR_UNSPECIFIED"
      case .equal: return "KEY_OPERATOR_EQUAL"
      case .exists: return "KEY_OPERATOR_EXISTS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:KeyOperator/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "KEY_OPERATOR_UNSPECIFIED": self = .unspecified
      case "KEY_OPERATOR_EQUAL": self = .equal
      case "KEY_OPERATOR_EXISTS": self = .exists
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:KeyOperator/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .equal
      case 2: self = .exists
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("KEY_OPERATOR_UNSPECIFIED")
      case .equal: return try container.encode("KEY_OPERATOR_EQUAL")
      case .exists: return try container.encode("KEY_OPERATOR_EXISTS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Effect indicates the taint effect to match e.g. 'NoSchedule'.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Effect: Codable, Equatable, Hashable, Sendable {
    /// Effect is not specified.
    case unspecified
    /// Effect maps to 'NoSchedule'.
    case noSchedule
    /// Effect maps to 'PreferNoSchedule'.
    case preferNoSchedule
    /// Effect maps to 'NoExecute'.
    case noExecute
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .noSchedule: return 1
      case .preferNoSchedule: return 2
      case .noExecute: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EFFECT_UNSPECIFIED"
      case .noSchedule: return "EFFECT_NO_SCHEDULE"
      case .preferNoSchedule: return "EFFECT_PREFER_NO_SCHEDULE"
      case .noExecute: return "EFFECT_NO_EXECUTE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Effect/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EFFECT_UNSPECIFIED": self = .unspecified
      case "EFFECT_NO_SCHEDULE": self = .noSchedule
      case "EFFECT_PREFER_NO_SCHEDULE": self = .preferNoSchedule
      case "EFFECT_NO_EXECUTE": self = .noExecute
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Effect/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .noSchedule
      case 2: self = .preferNoSchedule
      case 3: self = .noExecute
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("EFFECT_UNSPECIFIED")
      case .noSchedule: return try container.encode("EFFECT_NO_SCHEDULE")
      case .preferNoSchedule: return try container.encode("EFFECT_PREFER_NO_SCHEDULE")
      case .noExecute: return try container.encode("EFFECT_NO_EXECUTE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.Toleration"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
