// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for `AwsClusters.UpdateAwsNodePool` method.
@available(*, deprecated)
public struct UpdateAwsNodePoolRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool]
  /// resource to update.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  public var awsNodePool: AwsNodePool? = nil

  /// If set, only validate the request, but don't actually update the node pool.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Required. Mask of fields to update. At least one path must be supplied in
  /// this field. The elements of the repeated paths field can only include these
  /// fields from [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool]:
  ///
  ///  *   `annotations`.
  ///  *   `version`.
  ///  *   `autoscaling.min_node_count`.
  ///  *   `autoscaling.max_node_count`.
  ///  *   `config.config_encryption.kms_key_arn`.
  ///  *   `config.security_group_ids`.
  ///  *   `config.root_volume.iops`.
  ///  *   `config.root_volume.throughput`.
  ///  *   `config.root_volume.kms_key_arn`.
  ///  *   `config.root_volume.volume_type`.
  ///  *   `config.root_volume.size_gib`.
  ///  *   `config.proxy_config`.
  ///  *   `config.proxy_config.secret_arn`.
  ///  *   `config.proxy_config.secret_version`.
  ///  *   `config.ssh_config`.
  ///  *   `config.ssh_config.ec2_key_pair`.
  ///  *   `config.instance_placement.tenancy`.
  ///  *   `config.iam_instance_profile`.
  ///  *   `config.labels`.
  ///  *   `config.tags`.
  ///  *   `config.autoscaling_metrics_collection`.
  ///  *   `config.autoscaling_metrics_collection.granularity`.
  ///  *   `config.autoscaling_metrics_collection.metrics`.
  ///  *   `config.instance_type`.
  ///  *   `management.auto_repair`.
  ///  *   `management`.
  ///  *   `update_settings`.
  ///  *   `update_settings.surge_settings`.
  ///  *   `update_settings.surge_settings.max_surge`.
  ///  *   `update_settings.surge_settings.max_unavailable`.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateAwsNodePoolRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateAwsNodePoolRequest().with { $0.awsNodePool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let awsNodePool = CodingKeys(stringValue: "awsNodePool")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")
    static let updateMask = CodingKeys(stringValue: "updateMask")

    static let _knownKeys: Set<Swift.String> = [
      "awsNodePool",
      "validateOnly",
      "updateMask",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.awsNodePool = try container.decodeIfPresent(AwsNodePool.self, forKey: .awsNodePool)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.awsNodePool, forKey: .awsNodePool)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `UpdateAwsNodePoolRequest`: `"type.googleapis.com/google.cloud.gkemulticloud.v1.UpdateAwsNodePoolRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.UpdateAwsNodePoolRequest"
  }

  /// Initialize an instance of `UpdateAwsNodePoolRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.gkemulticloud.v1.UpdateAwsNodePoolRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `UpdateAwsNodePoolRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
