// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for `AwsClusters.UpdateAwsCluster` method.
@available(*, deprecated)
public struct UpdateAwsClusterRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster]
  /// resource to update.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  public var awsCluster: AwsCluster? = nil

  /// If set, only validate the request, but do not actually update the cluster.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Required. Mask of fields to update. At least one path must be supplied in
  /// this field. The elements of the repeated paths field can only include these
  /// fields from [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster]:
  ///
  ///  *   `description`.
  ///  *   `annotations`.
  ///  *   `control_plane.version`.
  ///  *   `authorization.admin_users`.
  ///  *   `authorization.admin_groups`.
  ///  *   `binary_authorization.evaluation_mode`.
  ///  *   `control_plane.aws_services_authentication.role_arn`.
  ///  *   `control_plane.aws_services_authentication.role_session_name`.
  ///  *   `control_plane.config_encryption.kms_key_arn`.
  ///  *   `control_plane.instance_type`.
  ///  *   `control_plane.security_group_ids`.
  ///  *   `control_plane.proxy_config`.
  ///  *   `control_plane.proxy_config.secret_arn`.
  ///  *   `control_plane.proxy_config.secret_version`.
  ///  *   `control_plane.root_volume.size_gib`.
  ///  *   `control_plane.root_volume.volume_type`.
  ///  *   `control_plane.root_volume.iops`.
  ///  *   `control_plane.root_volume.throughput`.
  ///  *   `control_plane.root_volume.kms_key_arn`.
  ///  *   `control_plane.ssh_config`.
  ///  *   `control_plane.ssh_config.ec2_key_pair`.
  ///  *   `control_plane.instance_placement.tenancy`.
  ///  *   `control_plane.iam_instance_profile`.
  ///  *   `logging_config.component_config.enable_components`.
  ///  *   `control_plane.tags`.
  ///  *   `monitoring_config.managed_prometheus_config.enabled`.
  ///  *   `networking.per_node_pool_sg_rules_disabled`.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateAwsClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateAwsClusterRequest().with { $0.awsCluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let awsCluster = CodingKeys(stringValue: "awsCluster")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")
    static let updateMask = CodingKeys(stringValue: "updateMask")

    static let _knownKeys: Set<Swift.String> = [
      "awsCluster",
      "validateOnly",
      "updateMask",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.awsCluster = try container.decodeIfPresent(AwsCluster.self, forKey: .awsCluster)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.awsCluster, forKey: .awsCluster)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.UpdateAwsClusterRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
